name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Install dependencies
      run: make install

    - name: Build Docker image
      run: make build

    - name: Push Docker image
      run: make push

    - name: Run Docker container
      run: make run
      env:
        DOCKER_ID_USER: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_NAME: calculator_app

    - name: Wait for Flask to be ready
      run: |
        for i in {1..30}; do
          if docker exec calculator_app_container curl --silent --head --fail http://localhost:5000; then
            echo "Flask app is ready."
            break
          fi
          echo "Waiting for Flask app to be ready..."
          sleep 5
        done

    - name: Run tests
      run: make test stop
